### ISSUE TITLE
Please add the license file

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-docx-feedstock#1]
Sorry, forgot to mention this before merging at staged-recipes ( https://github.com/conda-forge/staged-recipes/pull/1263 ). It would be great if we include the license file. The motivation being many open source licenses require that they appear with the code. MIT is definitely one of these licenses. To do this for `python-docx`, it is simply a matter of adding the following.

```
  license_file: LICENSE
```

It would be nice to have this done in the feedstock with a corresponding build number bump. That way new packages will include the license and thus be compliant.

**Comment by nicoddemus** [comment]
This has been fixed in 0de49b50
